### ISSUE TITLE
Question for run plevel in Quartz

### ISSUE THREAD

**Issue by Zhihaoi** [Pfzuo/Level-Hashing#2]
When I run plevel in Quartz, I only get some debug messages like this:
![que](https://user-images.githubusercontent.com/24693931/51321653-508bb980-1a9e-11e9-9f9d-d05a794ffe45.png)
I set latency=true and debug level=5.
There are no print messages for program runs.
Would you have any suggestions on how to resolve this?
Thank you!

**Comment by Pfzuo** [comment]
It seems that this is the problem of Quartz .  Maybe you should check whether Quartz is installed and run correctly.
