### ISSUE TITLE
An possible bug in persistent_level_hashing/level_hashing.c

### ISSUE THREAD

**Issue by shiniaas** [Pfzuo/Level-Hashing#3]
in line 84
    uint64_t *ptr = (uint64_t *)&level;
    for(; ptr < (uint64_t *)&level + sizeof(level_hash); ptr = ptr + 64)
        pflush((uint64_t *)&ptr);
The type of ptr should be char* and pflush will flush a cacheline

**Comment by Pfzuo** [comment]
Thanks. It also works using uint64_t pointer.
