### ISSUE TITLE
A possible bug in persistent_level_hashing/level_hashing.c

### ISSUE THREAD

**Issue by shiniaas** [Pfzuo/Level-Hashing#5]
#3 
Using uint64_t pointer, ptr + 64 will stride the size of 64*sizeof(uint64_t) = 512B
So I think it should be (line 86 may be also wrong)
char *ptr = (char *)&level;
for(; ptr < (char *)&level + sizeof(level_hash); ptr = ptr + 64)
pflush(ptr);

**Comment by Pfzuo** [comment]
You are right. Thanks for reporting. The bug has been repaired.
