### ISSUE TITLE
Question about level_delete()

### ISSUE THREAD

**Issue by YalandHong** [Pfzuo/Level-Hashing#6]
Hello Dr.Zuo,

I'm reading your OSDI'18 paper. According to Section 3.3(2)(b), the system failure may result in duplicate KV items in Level Hash Table.
But in your code of `level_delete()` in `persistent_level_hashing/level_hashing.c`, it seems that the function only deletes the first KV item then immediately returns.
```c
if (GET_BIT(level->buckets[i][f_idx].token, j) != 0&&strcmp(level->buckets[i][f_idx].slot[j].key, key) == 0)
{
	SET_BIT(level->buckets[i][f_idx].token, j, 0);
	pflush((uint64_t *)&level->buckets[i][f_idx].token);
	level->level_item_num[i] --;
	asm_mfence();
	return 0;   // only delete the first KV item?
}
```
Or the code deals with the problem elsewhere?

Thanks!
Yaland Hong

**Comment by Pfzuo** [comment]
Hi Yaland,

In the current code version, we log moved items when insertions incur movements, as shown in Lines 644~649.  So, the duplicate items can be removed on recovery based on the log.         

-Pengfei

**Comment by YalandHong** [comment]
So, the duplicate KV items are actually not allowed in the current code. And the "Log-free Insertion" still uses logging when movement is triggered. Is it right?

**Comment by Pfzuo** [comment]
Actually, there are two implementation methods.
1) insertion does not use logging and deletion removes duplicates.
2) insertion uses logging.
As we find movements are not frequent and thus using logging has a negligible impact on the insertion performance, the current implementation uses logging.

**Comment by YalandHong** [comment]
OK. Thanks!
